config/routes.rb
Rails.application.routes.draw do
  resources :activities
	root 'home#home'
  devise_for :users

  get 'welcome', to:'home#welcome'
  get 'about', to:'home#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord

	belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
		
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :activities
 def self.current
		Thread.current[:user]
	end
	def self.current=(user)
		Thread.current[:user] = user
	end	
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_activity, only: [:show, :edit, :update, :destroy]
  before_action :set_current_user

  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all.where(user_id:current_user.id)
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
    unless User.current.id == Activity.find(params[:id]).user_id
      redirect_to root_url, :alert =>'You are not authorize to access this record' 
    end
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
    @activity = Activity.find(params[:id])
    unless User.current.id == @activity.user_id
      redirect_to root_url, :alert =>'You are not authorize to access this record' 
    end
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)
    @activity.user_id = current_user.id
    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:name, :date, :duration)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	def set_current_user
		User.current = current_user
	end	
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def home
		if user_signed_in?
			redirect_to activities_path
		else
			redirect_to :controller =>'home', :action=>'welcome'
		end
	end

	def welcome
	end
	def about
	end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/activities/_form.html.erb
<%= form_with(model: activity, local: true) do |form| %>
  <% if activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% activity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% @name = %w[Running Walking Cycling Swimming Cardio Hiking Football Basketball Volleyball Tennis]%>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.select :name, @name,{},{class:'form-control'} %>
  </div>

  <div class="form-group">
    <%= form.label :activity_Date %>
    <%= form.date_select :date, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :duration %>
    <%= form.number_field :duration, class:'form-control' %>
  </div>

  

  <div class="actions">
    <%= form.submit "Save Activity",:class => 'btn btn-info' %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing Activity</h1>

<%= render 'form', activity: @activity %>

<div class="center">
<%= link_to 'Show', @activity, class:'btn btn-primary' %> |
<%= link_to 'Back', activities_path, class:'btn btn-primary' %>
</div>

<hr>

app/views/activities/index.html.erb
<h1>Activities</h1>

<table class='table table-bordered'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Date</th>
      <th>Duration</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @activities.each do |activity| %>
      <tr>
        <td><%= activity.name %></td>
        <td><%= activity.date %></td>
        <td><%= activity.duration %></td>
        <td><%= link_to 'Show', activity %></td>
        <td><%= link_to 'Edit', edit_activity_path(activity) %></td>
        <td><%= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Activity', new_activity_path, class:'btn btn-primary' %>

<hr>

app/views/activities/new.html.erb
<h1>New Activity</h1>

<%= render 'form', activity: @activity %>

<div class="center"><%= link_to 'Back', activities_path, class:'btn btn-primary' %></div>

<hr>

app/views/activities/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @activity.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @activity.date %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @activity.duration %>
</p>

<%= link_to 'Edit', edit_activity_path(@activity), class:'btn btn-primary' %> |
<%= link_to 'Back', activities_path, class:'btn btn-primary' %>

<hr>

app/views/home/about.html.erb
<h1 class="display-4">About</h1>
<p>Move and Groove is a fitness activity application that makes it easy to track and organize daily workouts.</p>
<p>The application is easy to use and it only takes a minute to create a free account.</p>
<p><a href="/users/sign_up">Click here</a> to get started.</p>
<p>Thank you for using Move and Groove!</p>

app/views/home/home.html.erb
<h1>Home page</h1>

app/views/home/welcome.html.erb
<div class="jumbotron">
  <h1 class="display-4">Track your fitness activities and stay healthy!</h1>
  <hr class="my-4">
  <% if user_signed_in? %>
        <li class="btn btn-primary btn-lg">
        <%= link_to "My Activities", fitness_activities_path %>
        </li>
        <% else %>
          <div class="btn btn-primary btn-lg"><%= link_to "Login", new_user_session_path %></div>
  <% end %>
  
</div>

<div class="container">

<div class="row">
        <div class="col-12 col-md-6 col-lg-4 mb-5">
            <div class="card shadow-sm">
                <img class="card-img-top" src="https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/woman-walking-on-a-path-royalty-free-image-503818820-1538171480.jpg" alt="">
                <div class="card-body">
                  <h5 class="card-title">Walking</h5>
                  <p class="card-text">The cardiovascular benefits of walking are biologically plausible; like other forms of regular moderate exercise, walking improves cardiac risk factors such as cholesterol, blood pressure, diabetes, obesity, vascular stiffness and inflammation, and mental stress.</p>
                  <a href="https://www.health.harvard.edu/staying-healthy/walking-your-steps-to-health" class="btn btn-info" target="_blank">Read More</a>
                </div>
            </div>
        </div>
        <div class="col-12 col-md-6 col-lg-4 mb-5">
            <div class="card shadow-sm">
                <img class="card-img-top" src="https://www.silversurfers.com/wp-content/uploads/2013/12/bigstock-Female-swimmer-wearing-United-503937201.jpg" alt="">
                <div class="card-body">
                  <h5 class="card-title">Swimming</h5>
                  <p class="card-text">Swimming is a great workout because you need to move your whole body against the resistance of the water. Swimming is a good all-round activity because it: keeps your heart rate up but takes some of the impact stress off your body. builds endurance, muscle strength and cardiovascular fitness.</p>
                  <a href="https://www.betterhealth.vic.gov.au/health/healthyliving/swimming-health-benefits" class="btn btn-info" target="_blank">Read More</a>
                </div>
            </div>
        </div>
        <div class="col-12 col-md-6 col-lg-4 mb-5">
            <div class="card shadow-sm">
                <img class="card-img-top" src="https://www.healthyfamiliesbc.ca/sites/hfbcprox-prod.health.gov.bc.ca/files/styles/large/public/thumbnails/2013_07_25_TheHealthBenefitsofHiking.jpg?itok=702rftDM" alt="">
                <div class="card-body">
                  <h5 class="card-title">Hiking</h5>
                  <p class="card-text">Hiking is a powerful cardio workout that can lower your risk of heart disease, improve your blood pressure and blood sugar levels, boost bone density, since walking is a weight-bearing exercise, strengthen your core, improve balance and help control your weight.</p>
                  <a href="https://www.webmd.com/fitness-exercise/features/hiking-body-mind" class="btn btn-info" target="_blank">Read More</a>
                </div>
            </div>
        </div>
        <div class="col-12 col-md-6 col-lg-4 mb-5">
            <div class="card shadow-sm">
                <img class="card-img-top" src="https://www.thehealthsite.com/wp-content/uploads/2013/01/woman-running-marathon-page-upload.jpg" alt="">
                <div class="card-body">
                  <h5 class="card-title">Running</h5>
                  <p class="card-text">Since it improves aerobic fitness, running is a great way to help improve cardiovascular health. Plus, it burns calories and can build strength, among other things. There's also a long list of psychological benefits runners gain from their sport.</p>
                  <a href="https://www.businessinsider.com/health-benefits-of-running-2018-4" class="btn btn-info" target="_blank">Read More</a>
                </div>
            </div>
        </div>
        <div class="col-12 col-md-6 col-lg-4 mb-5">
            <div class="card shadow-sm">
                <img class="card-img-top" src="https://i2.wp.com/yruha.blog/wp-content/uploads/2018/11/bike-mountain-mountain-biking-trail-163491-1.jpeg?resize=730%2C486&ssl=1" alt="">
                <div class="card-body">
                  <h5 class="card-title">Biking</h5>
                  <p class="card-text">Cycling improves strength, balance and coordination. It may also help to prevent falls and fractures. Riding a bike is an ideal form of exercise if you have osteoarthritis, because it is a low-impact exercise that places little stress on joints.</p>
                  <a href="https://www.betterhealth.vic.gov.au/health/healthyliving/cycling-health-benefits" class="btn btn-info" target="_blank">Read More</a>
                </div>
            </div>
        </div>
        <div class="col-12 col-md-6 col-lg-4 mb-5">
            <div class="card shadow-sm">
                <img class="card-img-top" src="https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/701/p-1-cardio-workout-1516282523.jpg" alt="">
                <div class="card-body">
                  <h5 class="card-title">Cardio</h5>
                  <p class="card-text">Aerobic exercise, also known as “cardio” exercise, uses repetitive contraction of large muscle groups to get your heart beating faster and is the most beneficial type of exercise for your cardiovascular system. Regular cardio workouts can reduce the risk of heart disease and diabetes and lower your blood pressure and cholesterol.</p>
                  <a href="https://utswmed.org/medblog/heart-cardio-workouts/" class="btn btn-info" target="_blank">Read More</a>
                </div>
            </div>
        </div>
    </div>  
</div>	  
	</div>

app/views/layouts/_alerts.html.erb
<% if flash[:notice]%>
	<div class="alert alert-success">
		<button type="button" class="close" data-dismiss="alert">&times;</button>
		<%= flash[:notice]%>
	</div>
<% elsif flash[:error] %>
	<div class="alert alert-error">
		<button type="button" class="close" data-dismiss="alert">&times;</button>
		<%= flash[:error]%>
	</div>
<% elsif flash[:alert] %>
	<div class="alert ">
		<button type="button" class="close" data-dismiss="alert">&times;</button>
		<%= flash[:alert]%>
	</div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="row">
    <div class="col-6 col-md-5 col-lg-4">
      <ul class="list-group list-group-flush footer-links">
          
        <% if user_signed_in? %>
        <li class="list-group-item">
          <i class="fa fa-tasks"></i>
            <%= link_to "My Activities", activities_path %>
        </li>
          <li class="list-group-item">
            <i class="fa fa-user-circle"></i>
              <%= link_to "Account Info", edit_user_registration_path %>
          </li>
          <li class="list-group-item">
            <i class="fa fa-sign-out"></i>
              <%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li class="list-group-item">
            <i class="fa fa-user-plus" aria-hidden="true"></i>
              <%= link_to "Sign Up", new_user_registration_path %>
          </li>
          <li class="list-group-item">
            <i class="fa fa-sign-in" aria-hidden="true"></i>
              <%= link_to "Login", new_user_session_path %>
          </li>
        <% end %>
        </ul>

    </div>

    <div class="col-6 col-md-5 offset-md-2 col-lg-4 offset-lg-4">
      <ul class="list-group ml-auto footer-links">
        <li class="list-group-item border-bottom"><a href="https://www.self.com/topic/fitness-news" target="_blank">SELF - Fitness and Exercise</a></li>
        <li class="list-group-item border-bottom"><a href="https://www.sciencedaily.com/news/health_medicine/fitness/" target="_blank">Science Daily - Fitness and Wellness</a></li>
        <li class="list-group-item"><a href="https://www.health.com/fitness" target="_blank">Health Magazine - Fitness and Health</a></li>
      </ul>
    </div>
  </footer> 

app/views/layouts/_navigation.html.erb
 <nav class="navbar navbar-expand-md navbar-dark bg-info">
  <a class="navbar-brand" href="/"><img class="fav" src="http://timeoutsports.biz/wp-content/uploads/2018/02/cropped-time-out-sports-favicon.png"> Move and Groove</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto noblt">      
      <li><%= link_to "About", about_path %></li>
    </ul>
  <ul class="nav navbar-nav navbar-right">
    <% if user_signed_in? %>
    <li class="nav-item noblt">
        <i class="fa fa-tasks"></i>
      <%= link_to "My Activities", activities_path %>
      </li>
      <li class="nav-item noblt">
        <i class="fa fa-user-circle"></i>
      <%= link_to "Account Info", edit_user_registration_path %>
      </li>
      <li class="nav-item noblt">
        <i class="fa fa-sign-out"></i>
      <%= link_to "Logout", destroy_user_session_path, method: :delete %>
      </li>
    <% else %>
      <li class="nav-item noblt">
        <i class="fa fa-user-plus" aria-hidden="true"></i>
      <%= link_to "Sign Up", new_user_registration_path %>
      </li>
      <li class="nav-item noblt">
        <i class="fa fa-sign-in" aria-hidden="true"></i>
      <%= link_to "Login", new_user_session_path %>
      </li>
    <% end %>
  </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fitness Tracker</title>
    <%= csrf_meta_tags %>
  <link rel="icon" href="http://timeoutsports.biz/wp-content/uploads/2018/02/cropped-time-out-sports-favicon.png" type="image/png" sizes="16x16">
  <link href="https://fonts.googleapis.com/css?family=Nunito+Sans&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   
  <%= render "layouts/navigation"%>
  <%= render "layouts/alerts"%>
  <div class="container">
  
    <%= yield %>    

  </div>
  <%= render "layouts/footer"%>


 <div id="cprt" align="center">©2019 Move and Groove Inc.</div>
 <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>